[phases.setup]
nixPkgs = ["go", "nodejs", "pnpm", "gcc", "libc-dev"]

[phases.install]
cmds = ["cd frontend && pnpm install"]

[phases.build]
cmds = [
    "cd frontend && pnpm run build",
    "mkdir -p backend/static backend/uploads/avatars",
    "cp -r frontend/dist/* backend/static/",
    "cd backend && CGO_ENABLED=1 go build -ldflags='-w -s' -o out ."
]

[start]
cmd = "./backend/out"
