[phases.setup]
nixPkgs = ["go", "nodejs", "pnpm", "gcc", "libc-dev"]

[variables]
CGO_ENABLED = "1"
GOOS = "linux"
NIXPACKS_METADATA = "go"

[phases.install]
cmds = ["cd frontend && pnpm install"]

[phases.build]
cmds = [
    "cd frontend && pnpm run build",
    "rm -rf backend/static && mkdir -p backend/static backend/uploads/avatars",
    "cp -r frontend/dist/* backend/static/",
    "cd backend && go build -ldflags='-w -s' -o out main.go"
]

[start]
cmd = "./backend/out"
